name: mongo-exporter

services:
  database:
    container_name: mongo
    build:
      context: docker/mongo
    env_file: .env
    tty: true
    ports:
      - ${DB_PORT}:27017
    environment:
        MONGO_INITDB_DATABASE: ${DB_NAME}
    volumes:
      - mongo-data:/data/db
    networks:
      - mongo-exporter-network
  app:
    container_name: app
    build:
      # NOTE: Set the context to the current directory to have reference for go.mod, go.sum
      context: .
      dockerfile: docker/golang/Dockerfile
    env_file: .env
    depends_on:
      - database
    ports:
      - ${APP_PORT}:8080
    networks:
      - mongo-exporter-network
    environment:
      - MONGO_URI=mongodb://${DB_HOST}:${DB_PORT}

# Docker Volumes
volumes:
  mongo-data:

# Docker Networks
networks:
  mongo-exporter-network:
    name: mongo-exporter-network
