{
 "title": "Mongo Exporter",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Users",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "me_coll_test_users_inserts", "legendFormat": "inserts" },
    { "expr": "me_coll_test_users_removes", "legendFormat": "removes" },
    { "expr": "me_coll_test_users_updates", "legendFormat": "updates" },
    { "expr": "me_coll_test_users_queries", "legendFormat": "queries" }
   ]
  },
  {
   "title": "System",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "me_insert_total_opcounter", "legendFormat": "inserts" },
    { "expr": "me_delete_total_opcounter", "legendFormat": "deletes" },
    { "expr": "me_update_total_opcounter", "legendFormat": "updates" },
    { "expr": "me_query_total_opcounter", "legendFormat": "queries" }
   ]
  },
  {
   "title": "Connections",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "me_current_connections", "legendFormat": "current" },
    { "expr": "me_active_connections", "legendFormat": "active" },
    { "expr": "me_total_created_connections", "legendFormat": "total created" },
    { "expr": "me_available_connections", "legendFormat": "available" }
   ]
  },
  {
   "title": "RAM",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "me_resident_mib", "legendFormat": "resident" },
    { "expr": "me_virtual_mib", "legendFormat": "virtual" }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 7 },
   "targets": [
    {
     "expr": "rate(me_total_time_us[$__rate_interval]) / 1_000_000 * 100",
     "legendFormat": "total time"
    },
    {
     "expr": "rate(me_user_time_us[$__rate_interval]) / 1_000_000 * 100",
     "legendFormat": "user time"
    },
    {
     "expr": "rate(me_system_time_us[$__rate_interval]) / 1_000_000 * 100",
     "legendFormat": "system time"
    }
   ]
  }
 ]
}